model_checkpoint:
  _target_: lightning.pytorch.callbacks.ModelCheckpoint
  dirpath: "${work_dir}/logs/checkpoints"
  filename: "epoch_{epoch:03d}-val_acc_{val/acc:.4f}"
  monitor: "val/acc"
  mode: "max"
  save_top_k: 1
  auto_insert_metric_name: False

early_stopping:
  _target_: lightning.pytorch.callbacks.EarlyStopping
  monitor: "val/loss"
  patience: 5
  mode: "min"
  verbose: True