# @package _global_

defaults:
  - _self_
  - data: lung_cancer
  - model: timm_classifier
  - logger: mlflow
  - trainer: default
  - callbacks: default

# Global settings
seed: 42
project_name: "Lung-Cancer-Classification"
work_dir: ${hydra:runtime.cwd}

# Path to original data (Change this to your actual path)
data_dir: ${work_dir}/data/raw